[Build] CMake install Python dist-info
Part of #1088. Install a minimal dist-info alongside the Python sources.
This means attempting to overwrite a CMake installation using
`pip install` will error like:

> ERROR: Cannot uninstall openassetio 1.0.0a14, RECORD file not found.
> Hint: The package was installed by cmake.

* `INSTALLER` is used by `pip` to provide the competing packager name
  ("cmake" in the example hint above).
* `METADATA` is mandatory according to the docs. It has the minimal
  contents required to be valid.
* `REQUESTED` is an empty flag file to signal that the package was
  installed individually and not as a dependency of another. Just seemed
  cheap to provide, not really necessary.
* `top_level.txt` contains the top-level namespace names provided by the
  package. Another one that seemed cheap to provide and is not really
  necessary.

Constructing the `dist-info` directory name and the `Version` in the
`METADATA` file, requires the Python OpenAssetIO package version.
Rather than add another manual step to the release process, regex it out
of the `pyproject.toml` as part of the CMake configure step.

Optionally skip installing `.dist-info` metadata directory as part of
installing Python files using a new
`OPENASSETIO_ENABLE_PYTHON_INSTALL_DIST_INFO` CMake option.

Signed-off-by: David Feltell <david.feltell@foundry.com>