squash: Fix Windows undefined reference to CppPluginSystemManagerPlugin
Apparently we need to explicitly declare destructors even in subclasses.

Signed-off-by: David Feltell <david.feltell@foundry.com>