[Build] Pin CMake version used in wheel building
Latest CMake 3.29 PyPI package causes

> ModuleNotFoundError: No module named 'importlib_metadata'

in a fresh Python 3.7 environment. Luckily, we only (currently) need
CMake 3.27+.

Signed-off-by: David Feltell <david.feltell@foundry.com>