[CI] Use latest pip in test venv
Part of #182. Installing the pure Python component using pip 21.2.3
supplied by the Python 3.9 conan package resulted in the following
deprecation warning

> DEPRECATION: A future pip version will change local packages to be
> built in-place without first copying to a temporary directory. We
> recommend you use --use-feature=in-tree-build to test your packages
> with this new behavior before it becomes the default. pip 21.3 will
> remove support for this functionality. You can find discussion
> regarding this at https://github.com/pypa/pip/issues/7555.

This means that by default the entire project was copied (not just the
Python component) before building.

It also triggers an issue (possible bug in pip) if the docs have been
built prior to doing the install

```
ERROR: Could not install packages due to an OSError: [('/home/vagrant/op
enassetio/doc/node_modules/.bin/sass', '/tmp/pip-req-build-law4s_0w/doc/
node_modules/.bin/sass', "[Errno 22] Invalid argument: '/home/vagrant/op
enassetio/doc/node_modules/.bin/sass'")]
```

which is an initially confusing error since `doc/node_modules` has
nothing to do with the Python package.

The `--use-feature=in-tree-build` flag suggested in the warning was
added in pip 21.1 and removed (rather, ignored) only a couple of minor
versions later, in pip 21.3. See https://pip.pypa.io/en/stable/news/

So just upgrade pip to the latest version and use that, avoiding the
deprecation warning and the error, and reducing the install time as a
bonus.

Use `python -m pip` for the initial pip upgrade/install to handle badly
behaved Python installations that don't bundle pip in the venv by
default and instead use the system pip, e.g. the ASWF VFX CY22 Docker
image. This means the following will now work from the repo root

```
docker run -v `pwd`:/src aswf/ci-base:2022.2 bash -c '
  cd /src && cmake -S . -B build -DOPENASSETIO_ENABLE_TESTS=ON &&\
  cd build && ctest'
```

Since in-tree builds are now the default with the latest pip,
`pip install .` adds an annoying `build` directory in the root of the
repo. Changing this is surprisingly hard. The only solution appears to
be an override in a `setup.cfg` config file.

Signed-off-by: David Feltell <david.feltell@foundry.com>